<?php
/**
 * Country helper class
 *
 * @author Fabián Ruiz <fabian@dezero.es>
 * @link http://www.dezero.es
 * @copyright Copyright &copy; 2024 Fabián Ruiz
 */

namespace dezero\modules\settings\helpers;

use Dz;
use user\models\User;
use Yii;

/**
 * Helper class for working with countries
 */
class CountryHelper
{
    /**
     * Return country code list following ISO 3166-1 alpha-2 format
     *
     * @see https://gist.github.com/djaiss/2938259
     */
    public static function codeList($language_id = 'en') : array
    {
        // Country list in spanish
        if ( $language_id === 'es' )
        {
            return self::codeListSpanish();
        }

        // Country list in english
        return [
            "AF" => "Afghanistan",
            "AL" => "Albania",
            "DZ" => "Algeria",
            "AS" => "American Samoa",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AI" => "Anguilla",
            "AQ" => "Antarctica",
            "AG" => "Antigua and Barbuda",
            "AR" => "Argentina",
            "AM" => "Armenia",
            "AW" => "Aruba",
            "AU" => "Australia",
            "AT" => "Austria",
            "AZ" => "Azerbaijan",
            "BS" => "Bahamas",
            "BH" => "Bahrain",
            "BD" => "Bangladesh",
            "BB" => "Barbados",
            "BY" => "Belarus",
            "BE" => "Belgium",
            "BZ" => "Belize",
            "BJ" => "Benin",
            "BM" => "Bermuda",
            "BT" => "Bhutan",
            "BO" => "Bolivia",
            "BA" => "Bosnia and Herzegovina",
            "BW" => "Botswana",
            "BV" => "Bouvet Island",
            "BR" => "Brazil",
            "IO" => "British Indian Ocean Territory",
            "BN" => "Brunei Darussalam",
            "BG" => "Bulgaria",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "KH" => "Cambodia",
            "CM" => "Cameroon",
            "CA" => "Canada",
            "CV" => "Cape Verde",
            "KY" => "Cayman Islands",
            "CF" => "Central African Republic",
            "TD" => "Chad",
            "CL" => "Chile",
            "CN" => "China",
            "CX" => "Christmas Island",
            "CC" => "Cocos (Keeling) Islands",
            "CO" => "Colombia",
            "KM" => "Comoros",
            "CG" => "Congo",
            "CD" => "Congo, the Democratic Republic of the",
            "CK" => "Cook Islands",
            "CR" => "Costa Rica",
            "CI" => "Cote D'Ivoire",
            "HR" => "Croatia",
            "CU" => "Cuba",
            "CY" => "Cyprus",
            "CZ" => "Czech Republic",
            "DK" => "Denmark",
            "DJ" => "Djibouti",
            "DM" => "Dominica",
            "DO" => "Dominican Republic",
            "EC" => "Ecuador",
            "EG" => "Egypt",
            "SV" => "El Salvador",
            "GQ" => "Equatorial Guinea",
            "ER" => "Eritrea",
            "EE" => "Estonia",
            "ET" => "Ethiopia",
            "FK" => "Falkland Islands (Malvinas)",
            "FO" => "Faroe Islands",
            "FJ" => "Fiji",
            "FI" => "Finland",
            "FR" => "France",
            "GF" => "French Guiana",
            "PF" => "French Polynesia",
            "TF" => "French Southern Territories",
            "GA" => "Gabon",
            "GM" => "Gambia",
            "GE" => "Georgia",
            "DE" => "Germany",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GR" => "Greece",
            "GL" => "Greenland",
            "GD" => "Grenada",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GN" => "Guinea",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HT" => "Haiti",
            "HM" => "Heard Island and Mcdonald Islands",
            "VA" => "Holy See (Vatican City State)",
            "HN" => "Honduras",
            "HK" => "Hong Kong",
            "HU" => "Hungary",
            "IS" => "Iceland",
            "IN" => "India",
            "ID" => "Indonesia",
            "IR" => "Iran, Islamic Republic of",
            "IQ" => "Iraq",
            "IE" => "Ireland",
            "IL" => "Israel",
            "IT" => "Italy",
            "JM" => "Jamaica",
            "JP" => "Japan",
            "JO" => "Jordan",
            "KZ" => "Kazakhstan",
            "KE" => "Kenya",
            "KI" => "Kiribati",
            "KP" => "Korea, Democratic People's Republic of",
            "KR" => "Korea, Republic of",
            "KW" => "Kuwait",
            "KG" => "Kyrgyzstan",
            "LA" => "Lao People's Democratic Republic",
            "LV" => "Latvia",
            "LB" => "Lebanon",
            "LS" => "Lesotho",
            "LR" => "Liberia",
            "LY" => "Libyan Arab Jamahiriya",
            "LI" => "Liechtenstein",
            "LT" => "Lithuania",
            "LU" => "Luxembourg",
            "MO" => "Macao",
            "MK" => "Macedonia, the Former Yugoslav Republic of",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "MY" => "Malaysia",
            "MV" => "Maldives",
            "ML" => "Mali",
            "MT" => "Malta",
            "MH" => "Marshall Islands",
            "MQ" => "Martinique",
            "MR" => "Mauritania",
            "MU" => "Mauritius",
            "YT" => "Mayotte",
            "MX" => "Mexico",
            "FM" => "Micronesia, Federated States of",
            "MD" => "Moldova, Republic of",
            "MC" => "Monaco",
            "ME" => "Montenegro",
            "MN" => "Mongolia",
            "MS" => "Montserrat",
            "MA" => "Morocco",
            "MZ" => "Mozambique",
            "MM" => "Myanmar",
            "NA" => "Namibia",
            "NR" => "Nauru",
            "NP" => "Nepal",
            "NL" => "Netherlands",
            "AN" => "Netherlands Antilles",
            "NC" => "New Caledonia",
            "NZ" => "New Zealand",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigeria",
            "NU" => "Niue",
            "NF" => "Norfolk Island",
            "MP" => "Northern Mariana Islands",
            "NO" => "Norway",
            "OM" => "Oman",
            "PK" => "Pakistan",
            "PW" => "Palau",
            "PS" => "Palestinian Territory, Occupied",
            "PA" => "Panama",
            "PG" => "Papua New Guinea",
            "PY" => "Paraguay",
            "PE" => "Peru",
            "PH" => "Philippines",
            "PN" => "Pitcairn",
            "PL" => "Poland",
            "PT" => "Portugal",
            "PR" => "Puerto Rico",
            "QA" => "Qatar",
            "RE" => "Reunion",
            "RO" => "Romania",
            "RS" => "Serbia",
            "RU" => "Russian Federation",
            "RW" => "Rwanda",
            "SH" => "Saint Helena",
            "KN" => "Saint Kitts and Nevis",
            "LC" => "Saint Lucia",
            "PM" => "Saint Pierre and Miquelon",
            "VC" => "Saint Vincent and the Grenadines",
            "WS" => "Samoa",
            "SM" => "San Marino",
            "ST" => "Sao Tome and Principe",
            "SA" => "Saudi Arabia",
            "SN" => "Senegal",
            "SC" => "Seychelles",
            "SL" => "Sierra Leone",
            "SG" => "Singapore",
            "SK" => "Slovakia",
            "SI" => "Slovenia",
            "SB" => "Solomon Islands",
            "SO" => "Somalia",
            "ZA" => "South Africa",
            "GS" => "South Georgia and the South Sandwich Islands",
            "ES" => "Spain",
            "LK" => "Sri Lanka",
            "SD" => "Sudan",
            "SR" => "Suriname",
            "SJ" => "Svalbard and Jan Mayen",
            "SZ" => "Swaziland",
            "SE" => "Sweden",
            "CH" => "Switzerland",
            "SY" => "Syrian Arab Republic",
            "TW" => "Taiwan, Province of China",
            "TJ" => "Tajikistan",
            "TZ" => "Tanzania, United Republic of",
            "TH" => "Thailand",
            "TL" => "Timor-Leste",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinidad and Tobago",
            "TN" => "Tunisia",
            "TR" => "Turkey",
            "TM" => "Turkmenistan",
            "TC" => "Turks and Caicos Islands",
            "TV" => "Tuvalu",
            "UG" => "Uganda",
            "UA" => "Ukraine",
            "AE" => "United Arab Emirates",
            "GB" => "United Kingdom",
            "US" => "United States",
            "UM" => "United States Minor Outlying Islands",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VU" => "Vanuatu",
            "VE" => "Venezuela",
            "VN" => "Viet Nam",
            "VG" => "Virgin Islands, British",
            "VI" => "Virgin Islands, U.s.",
            "WF" => "Wallis and Futuna",
            "EH" => "Western Sahara",
            "YE" => "Yemen",
            "ZM" => "Zambia",
            "ZW" => "Zimbabwe"
        ];
    }


    /**
     * Country code list translated to SPANISH language
     *
     * @see https://gist.github.com/djaiss/2938259
     */
    public static function codeListSpanish() : array
    {
        return [
            'AC' => 'Isla de la Ascensión',
            'AD' => 'Andorra',
            'AE' => 'Emiratos Árabes Unidos',
            'AF' => 'Afganistán',
            'AG' => 'Antigua y Barbuda',
            'AI' => 'Anguila',
            'AL' => 'Albania',
            'AM' => 'Armenia',
            'AN' => 'Antillas Neerlandesas',
            'AO' => 'Angola',
            'AQ' => 'Antártida',
            'AR' => 'Argentina',
            'AS' => 'Samoa Americana',
            'AT' => 'Austria',
            'AU' => 'Australia',
            'AW' => 'Aruba',
            'AX' => 'Islas Åland',
            'AZ' => 'Azerbaiyán',
            'BA' => 'Bosnia-Herzegovina',
            'BB' => 'Barbados',
            'BD' => 'Bangladesh',
            'BE' => 'Bélgica',
            'BF' => 'Burkina Faso',
            'BG' => 'Bulgaria',
            'BH' => 'Bahréin',
            'BI' => 'Burundi',
            'BJ' => 'Benín',
            'BL' => 'San Bartolomé',
            'BM' => 'Bermudas',
            'BN' => 'Brunéi',
            'BO' => 'Bolivia',
            'BQ' => 'Caribe neerlandés',
            'BR' => 'Brasil',
            'BS' => 'Bahamas',
            'BT' => 'Bután',
            'BV' => 'Isla Bouvet',
            'BW' => 'Botsuana',
            'BY' => 'Bielorrusia',
            'BZ' => 'Belice',
            'CA' => 'Canadá',
            'CC' => 'Islas Cocos',
            'CD' => 'Congo [República Democrática del Congo]',
            'CF' => 'República Centroafricana',
            'CG' => 'Congo [República]',
            'CH' => 'Suiza',
            'CI' => 'Costa de Marfil',
            'CK' => 'Islas Cook',
            'CL' => 'Chile',
            'CM' => 'Camerún',
            'CN' => 'China',
            'CO' => 'Colombia',
            'CP' => 'Isla Clipperton',
            'CR' => 'Costa Rica',
            'CU' => 'Cuba',
            'CV' => 'Cabo Verde',
            'CW' => 'Curazao',
            'CX' => 'Isla Christmas',
            'CY' => 'Chipre',
            'CZ' => 'República Checa',
            'DE' => 'Alemania',
            'DG' => 'Diego García',
            'DJ' => 'Yibuti',
            'DK' => 'Dinamarca',
            'DM' => 'Dominica',
            'DO' => 'República Dominicana',
            'DZ' => 'Argelia',
            'EA' => 'Ceuta y Melilla',
            'EC' => 'Ecuador',
            'EE' => 'Estonia',
            'EG' => 'Egipto',
            'EH' => 'Sáhara Occidental',
            'ER' => 'Eritrea',
            'ES' => 'España',
            'ET' => 'Etiopía',
            'EU' => 'Unión Europea',
            'FI' => 'Finlandia',
            'FJ' => 'Fiyi',
            'FK' => 'Islas Malvinas [Islas Falkland]',
            'FM' => 'Micronesia',
            'FO' => 'Islas Feroe',
            'FR' => 'Francia',
            'GA' => 'Gabón',
            'GB' => 'Reino Unido',
            'GD' => 'Granada',
            'GE' => 'Georgia',
            'GF' => 'Guayana Francesa',
            'GG' => 'Guernsey',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GL' => 'Groenlandia',
            'GM' => 'Gambia',
            'GN' => 'Guinea',
            'GP' => 'Guadalupe',
            'GQ' => 'Guinea Ecuatorial',
            'GR' => 'Grecia',
            'GS' => 'Islas Georgia del Sur y Sandwich del Sur',
            'GT' => 'Guatemala',
            'GU' => 'Guam',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HK' => 'Hong Kong',
            'HM' => 'Islas Heard y McDonald',
            'HN' => 'Honduras',
            'HR' => 'Croacia',
            'HT' => 'Haití',
            'HU' => 'Hungría',
            'IC' => 'Islas Canarias',
            'ID' => 'Indonesia',
            'IE' => 'Irlanda',
            'IL' => 'Israel',
            'IM' => 'Isla de Man',
            'IN' => 'India',
            'IO' => 'Territorio Británico del Océano Índico',
            'IQ' => 'Iraq',
            'IR' => 'Irán',
            'IS' => 'Islandia',
            'IT' => 'Italia',
            'JE' => 'Jersey',
            'JM' => 'Jamaica',
            'JO' => 'Jordania',
            'JP' => 'Japón',
            'KE' => 'Kenia',
            'KG' => 'Kirguistán',
            'KH' => 'Camboya',
            'KI' => 'Kiribati',
            'KM' => 'Comoras',
            'KN' => 'San Cristóbal y Nieves',
            'KP' => 'Corea del Norte',
            'KR' => 'Corea del Sur',
            'KW' => 'Kuwait',
            'KY' => 'Islas Caimán',
            'KZ' => 'Kazajistán',
            'LA' => 'Laos',
            'LB' => 'Líbano',
            'LC' => 'Santa Lucía',
            'LI' => 'Liechtenstein',
            'LK' => 'Sri Lanka',
            'LR' => 'Liberia',
            'LS' => 'Lesoto',
            'LT' => 'Lituania',
            'LU' => 'Luxemburgo',
            'LV' => 'Letonia',
            'LY' => 'Libia',
            'MA' => 'Marruecos',
            'MC' => 'Mónaco',
            'MD' => 'Moldavia',
            'ME' => 'Montenegro',
            'MF' => 'San Martín',
            'MG' => 'Madagascar',
            'MH' => 'Islas Marshall',
            'MK' => 'Macedonia [ERYM]',
            'ML' => 'Mali',
            'MM' => 'Myanmar [Birmania]',
            'MN' => 'Mongolia',
            'MO' => 'Macao',
            'MP' => 'Islas Marianas del Norte',
            'MQ' => 'Martinica',
            'MR' => 'Mauritania',
            'MS' => 'Montserrat',
            'MT' => 'Malta',
            'MU' => 'Mauricio',
            'MV' => 'Maldivas',
            'MW' => 'Malaui',
            'MX' => 'México',
            'MY' => 'Malasia',
            'MZ' => 'Mozambique',
            'NA' => 'Namibia',
            'NC' => 'Nueva Caledonia',
            'NE' => 'Níger',
            'NF' => 'Isla Norfolk',
            'NG' => 'Nigeria',
            'NI' => 'Nicaragua',
            'NL' => 'Países Bajos',
            'NO' => 'Noruega',
            'NP' => 'Nepal',
            'NR' => 'Nauru',
            'NU' => 'Isla Niue',
            'NZ' => 'Nueva Zelanda',
            'OM' => 'Omán',
            'PA' => 'Panamá',
            'PE' => 'Perú',
            'PF' => 'Polinesia Francesa',
            'PG' => 'Papúa Nueva Guinea',
            'PH' => 'Filipinas',
            'PK' => 'Pakistán',
            'PL' => 'Polonia',
            'PM' => 'San Pedro y Miquelón',
            'PN' => 'Islas Pitcairn',
            'PR' => 'Puerto Rico',
            'PS' => 'Palestina',
            'PT' => 'Portugal',
            'PW' => 'Palau',
            'PY' => 'Paraguay',
            'QA' => 'Qatar',
            'QO' => 'Territorios alejados de Oceanía',
            'RE' => 'Reunión',
            'RO' => 'Rumanía',
            'RS' => 'Serbia',
            'RU' => 'Rusia',
            'RW' => 'Ruanda',
            'SA' => 'Arabia Saudí',
            'SB' => 'Islas Salomón',
            'SC' => 'Seychelles',
            'SD' => 'Sudán',
            'SE' => 'Suecia',
            'SG' => 'Singapur',
            'SH' => 'Santa Elena',
            'SI' => 'Eslovenia',
            'SJ' => 'Svalbard y Jan Mayen',
            'SK' => 'Eslovaquia',
            'SL' => 'Sierra Leona',
            'SM' => 'San Marino',
            'SN' => 'Senegal',
            'SO' => 'Somalia',
            'SR' => 'Surinam',
            'SS' => 'Sudán del Sur',
            'ST' => 'Santo Tomé y Príncipe',
            'SV' => 'El Salvador',
            'SX' => 'Sint Maarten',
            'SY' => 'Siria',
            'SZ' => 'Suazilandia',
            'TA' => 'Tristán da Cunha',
            'TC' => 'Islas Turcas y Caicos',
            'TD' => 'Chad',
            'TF' => 'Territorios Australes Franceses',
            'TG' => 'Togo',
            'TH' => 'Tailandia',
            'TJ' => 'Tayikistán',
            'TK' => 'Tokelau',
            'TL' => 'Timor Oriental',
            'TM' => 'Turkmenistán',
            'TN' => 'Túnez',
            'TO' => 'Tonga',
            'TR' => 'Turquía',
            'TT' => 'Trinidad y Tobago',
            'TV' => 'Tuvalu',
            'TW' => 'Taiwán',
            'TZ' => 'Tanzania',
            'UA' => 'Ucrania',
            'UG' => 'Uganda',
            'UM' => 'Islas menores alejadas de los Estados Unidos',
            'US' => 'EE. UU.',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistán',
            'VA' => 'Ciudad del Vaticano',
            'VC' => 'San Vicente y las Granadinas',
            'VE' => 'Venezuela',
            'VG' => 'Islas Vírgenes Británicas',
            'VI' => 'Islas Vírgenes de los Estados Unidos',
            'VN' => 'Vietnam',
            'VU' => 'Vanuatu',
            'WF' => 'Wallis y Futuna',
            'WS' => 'Samoa',
            'XK' => 'Kosovo',
            'YE' => 'Yemen',
            'YT' => 'Mayotte',
            'ZA' => 'Sudáfrica',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabue',
        ];
    }


    /**
     * Array mapping ISO 3166-1 countries from alpha-2 to alpha-3
     *
     * @see https://gist.github.com/diegogurpegui/0476f17d3f01a7f79246c454876bdb9e
     */
    public static function mapAlpha3List() : array
    {
        return [
            'AC' => 'ASC',
            'AF' => 'AFG',
            'AX' => 'ALA',
            'AL' => 'ALB',
            'DZ' => 'DZA',
            'AS' => 'ASM',
            'AD' => 'AND',
            'AO' => 'AGO',
            'AI' => 'AIA',
            'AQ' => 'ATA',
            'AG' => 'ATG',
            'AR' => 'ARG',
            'AM' => 'ARM',
            'AW' => 'ABW',
            'AU' => 'AUS',
            'AT' => 'AUT',
            'AZ' => 'AZE',
            'BS' => 'BHS',
            'BH' => 'BHR',
            'BD' => 'BGD',
            'BB' => 'BRB',
            'BY' => 'BLR',
            'BE' => 'BEL',
            'BZ' => 'BLZ',
            'BJ' => 'BEN',
            'BM' => 'BMU',
            'BT' => 'BTN',
            'BO' => 'BOL',
            'BA' => 'BIH',
            'BW' => 'BWA',
            'BV' => 'BVT',
            'BR' => 'BRA',
            'VG' => 'VGB',
            'IO' => 'IOT',
            'BN' => 'BRN',
            'BG' => 'BGR',
            'BF' => 'BFA',
            'BI' => 'BDI',
            'KH' => 'KHM',
            'CM' => 'CMR',
            'CA' => 'CAN',
            'CP' => 'CPT',
            'CV' => 'CPV',
            'KY' => 'CYM',
            'CF' => 'CAF',
            'TD' => 'TCD',
            'CL' => 'CHL',
            'CN' => 'CHN',
            'HK' => 'HKG',
            'MO' => 'MAC',
            'CX' => 'CXR',
            'CC' => 'CCK',
            'CO' => 'COL',
            'KM' => 'COM',
            'CG' => 'COG',
            'CD' => 'COD',
            'CK' => 'COK',
            'CR' => 'CRI',
            'CI' => 'CIV',
            'HR' => 'HRV',
            'CU' => 'CUB',
            'CY' => 'CYP',
            'CZ' => 'CZE',
            'DK' => 'DNK',
            'DJ' => 'DJI',
            'DM' => 'DMA',
            'DO' => 'DOM',
            'EC' => 'ECU',
            'EG' => 'EGY',
            'SV' => 'SLV',
            'GQ' => 'GNQ',
            'ER' => 'ERI',
            'EE' => 'EST',
            'ET' => 'ETH',
            'FK' => 'FLK',
            'FO' => 'FRO',
            'FJ' => 'FJI',
            'FI' => 'FIN',
            'FR' => 'FRA',
            'GF' => 'GUF',
            'PF' => 'PYF',
            'TF' => 'ATF',
            'GA' => 'GAB',
            'GM' => 'GMB',
            'GE' => 'GEO',
            'DE' => 'DEU',
            'GH' => 'GHA',
            'GI' => 'GIB',
            'GR' => 'GRC',
            'GL' => 'GRL',
            'GD' => 'GRD',
            'GP' => 'GLP',
            'GU' => 'GUM',
            'GT' => 'GTM',
            'GG' => 'GGY',
            'GN' => 'GIN',
            'GW' => 'GNB',
            'GY' => 'GUY',
            'HT' => 'HTI',
            'HM' => 'HMD',
            'VA' => 'VAT',
            'HN' => 'HND',
            'HU' => 'HUN',
            'IS' => 'ISL',
            'IN' => 'IND',
            'ID' => 'IDN',
            'IR' => 'IRN',
            'IQ' => 'IRQ',
            'IE' => 'IRL',
            'IM' => 'IMN',
            'IL' => 'ISR',
            'IT' => 'ITA',
            'JM' => 'JAM',
            'JP' => 'JPN',
            'JE' => 'JEY',
            'JO' => 'JOR',
            'KZ' => 'KAZ',
            'KE' => 'KEN',
            'KI' => 'KIR',
            'KP' => 'PRK',
            'KR' => 'KOR',
            'KW' => 'KWT',
            'KG' => 'KGZ',
            'LA' => 'LAO',
            'LV' => 'LVA',
            'LB' => 'LBN',
            'LS' => 'LSO',
            'LR' => 'LBR',
            'LY' => 'LBY',
            'LI' => 'LIE',
            'LT' => 'LTU',
            'LU' => 'LUX',
            'MK' => 'MKD',
            'MG' => 'MDG',
            'MW' => 'MWI',
            'MY' => 'MYS',
            'MV' => 'MDV',
            'ML' => 'MLI',
            'MT' => 'MLT',
            'MH' => 'MHL',
            'MQ' => 'MTQ',
            'MR' => 'MRT',
            'MU' => 'MUS',
            'YT' => 'MYT',
            'MX' => 'MEX',
            'FM' => 'FSM',
            'MD' => 'MDA',
            'MC' => 'MCO',
            'MN' => 'MNG',
            'ME' => 'MNE',
            'MS' => 'MSR',
            'MA' => 'MAR',
            'MZ' => 'MOZ',
            'MM' => 'MMR',
            'NA' => 'NAM',
            'NR' => 'NRU',
            'NP' => 'NPL',
            'NL' => 'NLD',
            'AN' => 'ANT',
            'NC' => 'NCL',
            'NZ' => 'NZL',
            'NI' => 'NIC',
            'NE' => 'NER',
            'NG' => 'NGA',
            'NU' => 'NIU',
            'NF' => 'NFK',
            'MP' => 'MNP',
            'NO' => 'NOR',
            'OM' => 'OMN',
            'PK' => 'PAK',
            'PW' => 'PLW',
            'PS' => 'PSE',
            'PA' => 'PAN',
            'PG' => 'PNG',
            'PY' => 'PRY',
            'PE' => 'PER',
            'PH' => 'PHL',
            'PN' => 'PCN',
            'PL' => 'POL',
            'PT' => 'PRT',
            'PR' => 'PRI',
            'QA' => 'QAT',
            'RE' => 'REU',
            'RO' => 'ROU',
            'RU' => 'RUS',
            'RW' => 'RWA',
            'BL' => 'BLM',
            'SH' => 'SHN',
            'KN' => 'KNA',
            'LC' => 'LCA',
            'MF' => 'MAF',
            'PM' => 'SPM',
            'VC' => 'VCT',
            'WS' => 'WSM',
            'SM' => 'SMR',
            'ST' => 'STP',
            'SA' => 'SAU',
            'SN' => 'SEN',
            'RS' => 'SRB',
            'SC' => 'SYC',
            'SL' => 'SLE',
            'SG' => 'SGP',
            'SK' => 'SVK',
            'SI' => 'SVN',
            'SB' => 'SLB',
            'SO' => 'SOM',
            'ZA' => 'ZAF',
            'GS' => 'SGS',
            'SS' => 'SSD',
            'ES' => 'ESP',
            'LK' => 'LKA',
            'SD' => 'SDN',
            'SR' => 'SUR',
            'SJ' => 'SJM',
            'SZ' => 'SWZ',
            'SE' => 'SWE',
            'CH' => 'CHE',
            'SY' => 'SYR',
            'TW' => 'TWN',
            'TJ' => 'TJK',
            'TZ' => 'TZA',
            'TH' => 'THA',
            'TL' => 'TLS',
            'TG' => 'TGO',
            'TK' => 'TKL',
            'TO' => 'TON',
            'TT' => 'TTO',
            'TN' => 'TUN',
            'TR' => 'TUR',
            'TM' => 'TKM',
            'TC' => 'TCA',
            'TV' => 'TUV',
            'UG' => 'UGA',
            'UA' => 'UKR',
            'AE' => 'ARE',
            'GB' => 'GBR',
            'US' => 'USA',
            'UM' => 'UMI',
            'UY' => 'URY',
            'UZ' => 'UZB',
            'VU' => 'VUT',
            'VE' => 'VEN',
            'VN' => 'VNM',
            'VI' => 'VIR',
            'WF' => 'WLF',
            'EH' => 'ESH',
            'YE' => 'YEM',
            'ZM' => 'ZMB',
            'ZW' => 'ZWE'
        ];

    }


    /**
     * Mapping arrays for countries ISO 3166-1 from alpha-2 code to alpha-3
     *
     * @see https://gist.github.com/diegogurpegui/0476f17d3f01a7f79246c454876bdb9e
     */
    public static function alpha3Code($country_alpha2_code = null) : ?array
    {
        $vec_alpha3_list = self::mapAlpha3List();

        // Given a specific country code
        if ( $country_alpha2_code !== null )
        {
            if ( isset($vec_alpha3_list[$country_alpha2_code]) )
            {
                return $vec_alpha3_list[$country_alpha2_code];
            }

            return null;
        }

        // Return all the mapping array
        return $vec_alpha3_list;
    }


    /**
     * Mapping arrays for countries ISO 3166-1 from alpha-3 code to alpha-2
     */
    public static function alpha2Code($country_alpha3_code = null) : ?array
    {
        $vec_alpha3_list = self::mapAlpha3List();
        $vec_alpha3_list = array_flip($vec_alpha3_list);

        // Given a specific country code
        if ( $country_alpha3_code !== null )
        {
            if ( isset($vec_alpha3_list[$country_alpha3_code]) )
            {
                return $vec_alpha3_list[$country_alpha3_code];
            }

            return null;
        }

        // Return all the mapping array
        return $vec_alpha3_list;
    }
}
