<?php
/**
 * Base Entity model class file
 *
 * @author Fabián Ruiz <fabian@dezero.es>
 * @link http://www.dezero.es
 * @copyright Copyright &copy; 2024 Fabián Ruiz
 */

namespace dezero\modules\entity\models\base;

use dezero\modules\entity\models\query\EntityQuery;
use yii\db\ActiveQueryInterface;
use Yii;

/**
 * DO NOT MODIFY THIS FILE! It is automatically generated by Gii.
 * If any changes are necessary, you must set or override the required
 * property or method in class "dezero\modules\entity\models\Entity".
 *
 * Base Entity model class for table "entity_entity".
 *
 * -------------------------------------------------------------------------
 * COLUMN ATTRIBUTES
 * -------------------------------------------------------------------------
 * @property string $entity_uuid
 * @property string $entity_type
 * @property int $source_id
 * @property string $source_name
 * @property string $module_name
 */
abstract class Entity extends \dezero\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName() : string
    {
        return 'entity_entity';
    }


    /**
     * {@inheritdoc}
     */
    public function rules() : array
    {
        return [
            // Typed rules
            'requiredFields' => [['entity_type', 'source_name', 'module_name'], 'required'],
            'integerFields' => [['source_id'], 'integer'],

            // Max length rules
            'max32' => [['source_name', 'module_name'], 'string', 'max' => 32],
            'max36' => [['entity_uuid'], 'string', 'max' => 36],
            'max128' => [['entity_type'], 'string', 'max' => 128],

            // Default NULL
            'defaultNull' => [['source_id'], 'default', 'value' => null],

            // UNIQUE rules
            'entityUuidUnique' => [['entity_uuid'], 'unique'],
        ];
    }


    /**
     * @return EntityQuery The ActiveQuery class for this model
     */
    public static function find() : EntityQuery
    {
        return new EntityQuery(static::class);
    }


    /**
     * Title used for this model
     */
    public function title() : string
    {
        return $this->entity_uuid;
    }
}
