<?php
/**
 * Base StatusHistory model class file
 *
 * @author Fabián Ruiz <fabian@dezero.es>
 * @link http://www.dezero.es
 * @copyright Copyright &copy; 2023 Fabián Ruiz
 */

namespace dezero\modules\entity\models\base;

use dezero\modules\entity\models\query\StatusHistoryQuery;
use yii\db\ActiveQueryInterface;
use Yii;

/**
 * DO NOT MODIFY THIS FILE! It is automatically generated by Gii.
 * If any changes are necessary, you must set or override the required
 * property or method in class "dezero\modules\entity\models\StatusHistory".
 *
 * Base StatusHistory model class for table "entity_status_history".
 *
 * -------------------------------------------------------------------------
 * COLUMN ATTRIBUTES
 * -------------------------------------------------------------------------
 * @property int $status_history_id
 * @property string $entity_type
 * @property string $entity_uuid
 * @property int $entity_source_id
 * @property string $status_type
 * @property string $comments
 * @property int $created_date
 * @property int $created_user_id
 */
abstract class StatusHistory extends \dezero\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName() : string
    {
        return 'entity_status_history';
    }


    /**
     * {@inheritdoc}
     */
    public function rules() : array
    {
        return [
            // Typed rules
            'requiredFields' => [['entity_type', 'status_type'], 'required'],
            'integerFields' => [['entity_source_id', 'created_date', 'created_user_id'], 'integer'],
            'stringFields' => [['comments'], 'string'],
            
            // Max length rules
            'max32' => [['status_type'], 'string', 'max' => 32],
            'max36' => [['entity_uuid'], 'string', 'max' => 36],
            'max128' => [['entity_type'], 'string', 'max' => 128],
            
            // Default NULL
            'defaultNull' => [['entity_source_id', 'comments'], 'default', 'value' => null],
        ];
    }




    /**
     * @return StatusHistoryQuery The ActiveQuery class for this model
     */
    public static function find() : StatusHistoryQuery
    {
        return new StatusHistoryQuery(static::class);
    }


    /**
     * Title used for this model
     */
    public function title() : string
    {
        return $this->entity_type;
    }
}
