<?php
/**
 * Base Batch model class file
 *
 * @author Fabián Ruiz <fabian@dezero.es>
 * @link http://www.dezero.es
 * @copyright Copyright &copy; 2024 Fabián Ruiz
 */

namespace dezero\modules\sync\models\base;

use dezero\modules\sync\models\query\BatchQuery;
use yii\db\ActiveQueryInterface;
use Yii;

/**
 * DO NOT MODIFY THIS FILE! It is automatically generated by Gii.
 * If any changes are necessary, you must set or override the required
 * property or method in class "dezero\modules\sync\models\Batch".
 *
 * Base Batch model class for table "batch".
 *
 * -------------------------------------------------------------------------
 * COLUMN ATTRIBUTES
 * -------------------------------------------------------------------------
 * @property int $batch_id
 * @property string $batch_type
 * @property string $name
 * @property string $description
 * @property int $total_items
 * @property int $total_errors
 * @property int $total_warnings
 * @property string $summary_json
 * @property string $results_json
 * @property int $total_operations
 * @property int $last_operation
 * @property int $item_starting_num
 * @property int $item_ending_num
 * @property int $file_id
 * @property string $entity_uuid
 * @property string $entity_type
 * @property int $entity_source_id
 * @property int $created_date
 * @property int $created_user_id
 * @property int $updated_date
 * @property int $updated_user_id
 *
 * -------------------------------------------------------------------------
 * RELATIONS
 * -------------------------------------------------------------------------
 * @property User $createdUser
 * @property Entity $entityUu
 * @property AssetFile $file
 * @property User $updatedUser
 */
abstract class Batch extends \dezero\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName() : string
    {
        return 'batch';
    }


    /**
     * {@inheritdoc}
     */
    public function rules() : array
    {
        return [
            // Typed rules
            'requiredFields' => [['batch_type', 'name'], 'required'],
            'integerFields' => [['total_items', 'total_errors', 'total_warnings', 'total_operations', 'last_operation', 'item_starting_num', 'item_ending_num', 'file_id', 'entity_source_id', 'created_date', 'created_user_id', 'updated_date', 'updated_user_id'], 'integer'],
            'stringFields' => [['summary_json', 'results_json'], 'string'],

            // Max length rules
            'max32' => [['batch_type'], 'string', 'max' => 32],
            'max36' => [['entity_uuid'], 'string', 'max' => 36],
            'max128' => [['name', 'entity_type'], 'string', 'max' => 128],
            'max255' => [['description'], 'string', 'max' => 255],

            // Default NULL
            'defaultNull' => [['description', 'summary_json', 'results_json', 'file_id', 'entity_uuid', 'entity_type', 'entity_source_id'], 'default', 'value' => null],
        ];
    }


    /**
     * @return BatchQuery The ActiveQuery class for this model
     */
    public static function find() : BatchQuery
    {
        return new BatchQuery(static::class);
    }


    /**
     * Title used for this model
     */
    public function title() : string
    {
        return $this->batch_type;
    }
}

/**
 * These are relations and enum methods generated with Gii.
 * YOU CAN USE THESE METHODS IN THE PARENT MODEL CLASS
 *

   /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    *

    /**
     * @return ActiveQueryInterface The relational query object.
     *
    public function getCreatedUser() : ActiveQueryInterface
    {
        return $this->hasOne(User::class, ['user_id' => 'created_user_id']);
    }


    /**
     * @return ActiveQueryInterface The relational query object.
     *
    public function getEntityUu() : ActiveQueryInterface
    {
        return $this->hasOne(Entity::class, ['entity_uuid' => 'entity_uuid']);
    }


    /**
     * @return ActiveQueryInterface The relational query object.
     *
    public function getFile() : ActiveQueryInterface
    {
        return $this->hasOne(AssetFile::class, ['file_id' => 'file_id']);
    }


    /**
     * @return ActiveQueryInterface The relational query object.
     *
    public function getUpdatedUser() : ActiveQueryInterface
    {
        return $this->hasOne(User::class, ['user_id' => 'updated_user_id']);
    }

*/
