<?php
/**
 * @author Fabián Ruiz <fabian@dezero.es>
 * @link http://www.dezero.es
 * @copyright Copyright &copy; 2023 Fabián Ruiz
 */

namespace dezero\grid;

use dezero\helpers\ArrayHelper;
use dezero\helpers\Html;
use Yii;

/**
 * ActionColumn is a column for the [[GridView]] widget that displays buttons for viewing and manipulating the items.
 */
class DataColumn extends \yii\grid\DataColumn
{
    /**
     * @var bool
     */
    public $select2Options;

    /**
     * @var string|array|Closure in which format should the value of each data model be displayed as (e.g. `"raw"`, `"text"`, `"html"`,
     * `['date', 'php:Y-m-d']`). Supported formats are determined by the [[GridView::formatter|formatter]] used by
     * the [[GridView]]. Default format is "text" which will format the value as an HTML-encoded plain text when
     * [[\yii\i18n\Formatter]] is used as the [[GridView::$formatter|formatter]] of the GridView.
     * @see \yii\i18n\Formatter::format()
     */
    public $format = 'html'; // 'text';


    /**
     * @var array the HTML attributes for the link tag in the header cell
     * generated by [[\yii\data\Sort::link]] when sorting is enabled for this column.
     * @see \yii\helpers\Html::renderTagAttributes() for details on how attributes are being rendered.
     */
    public $sortLinkOptions = [
        'class' => 'sort-link'
    ];


    /**
     * {@inheritdoc}
     */
    public function renderHeaderCell()
    {
        if ( $this->attribute !== null )
        {
            $vec_header_options = ['class' => $this->attribute .'_header'];
            if ( $this->enableSorting )
            {
                $vec_header_options['class'] .= ' sortable';
            }
            $this->headerOptions = ArrayHelper::merge($vec_header_options, $this->headerOptions);
        }

        return parent::renderHeaderCell();
    }


    /**
     * {@inheritdoc}
     */
    public function renderFilterCell()
    {
        if ( $this->attribute !== null )
        {
            $vec_filter_options = [
                'class' => $this->filterAttribute .'_filter',
                'id'    => $this->grid->id .'--'. $this->filterAttribute .'--filter',
            ];

            // Custom options for SELECT2 widget
            if ( $this->select2Options === null )
            {
                 $this->select2Options = [];
            }
            $this->select2Options['is_custom'] = $this->select2Options['is_custom'] ?? false;
            $this->select2Options['is_slidepanel'] = $this->select2Options['is_slidepanel'] ?? false;
            $this->select2Options['placeholder'] = $this->select2Options['placeholder'] ?? Yii::t('backend', '- All -');

            // Custom class to allow init SELECT2 via custom Javascript after Gridview update
            if ( $this->select2Options['is_custom'] === true )
            {
                $vec_filter_options['class'] .= ' select2-custom';
            }

            // Custom class for slidepanel
            if ( $this->select2Options['is_slidepanel'] === true )
            {
                $vec_filter_options['class'] .= ' select2-slidepanel';
            }

            // Custom placeholder
            if ( $this->select2Options['placeholder'] !== null )
            {
                $this->filterInputOptions['data-placeholder'] = $this->select2Options['placeholder'];
            }

            $this->filterOptions = ArrayHelper::merge($vec_filter_options, $this->filterOptions);
        }

        return parent::renderFilterCell();
    }


    /**
     * {@inheritdoc}
     */
    public function renderDataCell($model, $key, $index)
    {
        if ( $this->attribute !== null )
        {
            $this->contentOptions = ArrayHelper::merge(['class' => $this->attribute .'_column'], $this->contentOptions);
        }

        return parent::renderDataCell($model, $key, $index);
    }


    /**
     * {@inheritdoc}
     */
    public function renderFooterCell()
    {
        if ( $this->attribute !== null )
        {
            $this->footerOptions = ArrayHelper::merge(['class' => $this->attribute .'_footer'], $this->footerOptions);
        }

        return parent::renderFooterCell();
    }
}
